security:
    enable_authenticator_manager: true
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
             algorithm: auto

    providers:
        in_memory_users:
            memory:
                users:
                    admin:
                        password: '$2y$13$SVu5xypIpWAHdY3kfWbNYuTrCAuqZC1vEem1TsNlrHqsriAqMk6h.'
                        roles: ['ROLE_ADMIN']
                    user:
                        password: '$2y$13$DVB/TxiBt.eT2rJQXdvxVOcoJdyuE7ogldbp0/fBZF4X19IXcA72m'
                        roles: ['ROLE_USER']

    firewalls:
        login:
            pattern:  ^/api/login
            stateless: true
            json_login:
                check_path: /api/login
                username_path: username
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern:   ^/api
            stateless: true
            jwt: ~

    access_control:
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/books, roles: ROLE_USER }
